FROM  nginx:latest
LABEL version="0.0.1"
LABEL author="James Kokou GAGLO"
LABEL platfom="https://learn.garkado.com"
COPY index.html /usr/share/nginx/html
ADD https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css  /usr/share/nginx/html
